// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol_grpc.proto
// Protobuf C++ Version: 6.33.4

#ifndef protocol_5fgrpc_2eproto_2epb_2eh
#define protocol_5fgrpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protocol_5fgrpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_5fgrpc_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protocol_5fgrpc_2eproto;
}  // extern "C"
namespace Protocol {
class BuffMonsterHpAdminReq;
struct BuffMonsterHpAdminReqDefaultTypeInternal;
extern BuffMonsterHpAdminReqDefaultTypeInternal _BuffMonsterHpAdminReq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BuffMonsterHpAdminReq_class_data_;
class BuffMonsterHpAdminRes;
struct BuffMonsterHpAdminResDefaultTypeInternal;
extern BuffMonsterHpAdminResDefaultTypeInternal _BuffMonsterHpAdminRes_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BuffMonsterHpAdminRes_class_data_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {

// ===================================================================


// -------------------------------------------------------------------

class BuffMonsterHpAdminRes final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.BuffMonsterHpAdminRes) */ {
 public:
  inline BuffMonsterHpAdminRes() : BuffMonsterHpAdminRes(nullptr) {}
  ~BuffMonsterHpAdminRes() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BuffMonsterHpAdminRes* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BuffMonsterHpAdminRes));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BuffMonsterHpAdminRes(::google::protobuf::internal::ConstantInitialized);

  inline BuffMonsterHpAdminRes(const BuffMonsterHpAdminRes& from) : BuffMonsterHpAdminRes(nullptr, from) {}
  inline BuffMonsterHpAdminRes(BuffMonsterHpAdminRes&& from) noexcept
      : BuffMonsterHpAdminRes(nullptr, ::std::move(from)) {}
  inline BuffMonsterHpAdminRes& operator=(const BuffMonsterHpAdminRes& from) {
    CopyFrom(from);
    return *this;
  }
  inline BuffMonsterHpAdminRes& operator=(BuffMonsterHpAdminRes&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BuffMonsterHpAdminRes& default_instance() {
    return *reinterpret_cast<const BuffMonsterHpAdminRes*>(
        &_BuffMonsterHpAdminRes_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BuffMonsterHpAdminRes& a, BuffMonsterHpAdminRes& b) { a.Swap(&b); }
  inline void Swap(BuffMonsterHpAdminRes* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BuffMonsterHpAdminRes* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BuffMonsterHpAdminRes* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BuffMonsterHpAdminRes>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BuffMonsterHpAdminRes& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BuffMonsterHpAdminRes& from) { BuffMonsterHpAdminRes::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BuffMonsterHpAdminRes* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.BuffMonsterHpAdminRes"; }

  explicit BuffMonsterHpAdminRes(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BuffMonsterHpAdminRes(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BuffMonsterHpAdminRes& from);
  BuffMonsterHpAdminRes(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BuffMonsterHpAdminRes&& from) noexcept
      : BuffMonsterHpAdminRes(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const ::std::string& message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.BuffMonsterHpAdminRes)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 46,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BuffMonsterHpAdminRes& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_5fgrpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BuffMonsterHpAdminRes_class_data_;
// -------------------------------------------------------------------

class BuffMonsterHpAdminReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.BuffMonsterHpAdminReq) */ {
 public:
  inline BuffMonsterHpAdminReq() : BuffMonsterHpAdminReq(nullptr) {}
  ~BuffMonsterHpAdminReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BuffMonsterHpAdminReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BuffMonsterHpAdminReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BuffMonsterHpAdminReq(::google::protobuf::internal::ConstantInitialized);

  inline BuffMonsterHpAdminReq(const BuffMonsterHpAdminReq& from) : BuffMonsterHpAdminReq(nullptr, from) {}
  inline BuffMonsterHpAdminReq(BuffMonsterHpAdminReq&& from) noexcept
      : BuffMonsterHpAdminReq(nullptr, ::std::move(from)) {}
  inline BuffMonsterHpAdminReq& operator=(const BuffMonsterHpAdminReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline BuffMonsterHpAdminReq& operator=(BuffMonsterHpAdminReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BuffMonsterHpAdminReq& default_instance() {
    return *reinterpret_cast<const BuffMonsterHpAdminReq*>(
        &_BuffMonsterHpAdminReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BuffMonsterHpAdminReq& a, BuffMonsterHpAdminReq& b) { a.Swap(&b); }
  inline void Swap(BuffMonsterHpAdminReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BuffMonsterHpAdminReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BuffMonsterHpAdminReq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BuffMonsterHpAdminReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BuffMonsterHpAdminReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BuffMonsterHpAdminReq& from) { BuffMonsterHpAdminReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BuffMonsterHpAdminReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.BuffMonsterHpAdminReq"; }

  explicit BuffMonsterHpAdminReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BuffMonsterHpAdminReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BuffMonsterHpAdminReq& from);
  BuffMonsterHpAdminReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BuffMonsterHpAdminReq&& from) noexcept
      : BuffMonsterHpAdminReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAddHpFieldNumber = 1,
  };
  // int32 add_hp = 1;
  void clear_add_hp() ;
  ::int32_t add_hp() const;
  void set_add_hp(::int32_t value);

  private:
  ::int32_t _internal_add_hp() const;
  void _internal_set_add_hp(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.BuffMonsterHpAdminReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BuffMonsterHpAdminReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t add_hp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_5fgrpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BuffMonsterHpAdminReq_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BuffMonsterHpAdminReq

// int32 add_hp = 1;
inline void BuffMonsterHpAdminReq::clear_add_hp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.add_hp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t BuffMonsterHpAdminReq::add_hp() const {
  // @@protoc_insertion_point(field_get:Protocol.BuffMonsterHpAdminReq.add_hp)
  return _internal_add_hp();
}
inline void BuffMonsterHpAdminReq::set_add_hp(::int32_t value) {
  _internal_set_add_hp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Protocol.BuffMonsterHpAdminReq.add_hp)
}
inline ::int32_t BuffMonsterHpAdminReq::_internal_add_hp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.add_hp_;
}
inline void BuffMonsterHpAdminReq::_internal_set_add_hp(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.add_hp_ = value;
}

// -------------------------------------------------------------------

// BuffMonsterHpAdminRes

// bool success = 1;
inline void BuffMonsterHpAdminRes::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool BuffMonsterHpAdminRes::success() const {
  // @@protoc_insertion_point(field_get:Protocol.BuffMonsterHpAdminRes.success)
  return _internal_success();
}
inline void BuffMonsterHpAdminRes::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.BuffMonsterHpAdminRes.success)
}
inline bool BuffMonsterHpAdminRes::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void BuffMonsterHpAdminRes::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// string message = 2;
inline void BuffMonsterHpAdminRes::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BuffMonsterHpAdminRes::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.BuffMonsterHpAdminRes.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BuffMonsterHpAdminRes::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.BuffMonsterHpAdminRes.message)
}
inline ::std::string* PROTOBUF_NONNULL BuffMonsterHpAdminRes::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:Protocol.BuffMonsterHpAdminRes.message)
  return _s;
}
inline const ::std::string& BuffMonsterHpAdminRes::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void BuffMonsterHpAdminRes::_internal_set_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BuffMonsterHpAdminRes::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BuffMonsterHpAdminRes::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.BuffMonsterHpAdminRes.message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void BuffMonsterHpAdminRes::set_allocated_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.BuffMonsterHpAdminRes.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // protocol_5fgrpc_2eproto_2epb_2eh
