// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol_grpc.proto
// Protobuf C++ Version: 6.33.4

#include "protocol_grpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr BuffMonsterHpAdminRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false} {}

template <typename>
PROTOBUF_CONSTEXPR BuffMonsterHpAdminRes::BuffMonsterHpAdminRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BuffMonsterHpAdminRes_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BuffMonsterHpAdminResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuffMonsterHpAdminResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuffMonsterHpAdminResDefaultTypeInternal() {}
  union {
    BuffMonsterHpAdminRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuffMonsterHpAdminResDefaultTypeInternal _BuffMonsterHpAdminRes_default_instance_;

inline constexpr BuffMonsterHpAdminReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        add_hp_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BuffMonsterHpAdminReq::BuffMonsterHpAdminReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BuffMonsterHpAdminReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BuffMonsterHpAdminReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuffMonsterHpAdminReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuffMonsterHpAdminReqDefaultTypeInternal() {}
  union {
    BuffMonsterHpAdminReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuffMonsterHpAdminReqDefaultTypeInternal _BuffMonsterHpAdminReq_default_instance_;
}  // namespace Protocol
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protocol_5fgrpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protocol_5fgrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_protocol_5fgrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffMonsterHpAdminReq, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffMonsterHpAdminReq, _impl_.add_hp_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffMonsterHpAdminRes, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffMonsterHpAdminRes, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffMonsterHpAdminRes, _impl_.message_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Protocol::BuffMonsterHpAdminReq)},
        {5, sizeof(::Protocol::BuffMonsterHpAdminRes)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Protocol::_BuffMonsterHpAdminReq_default_instance_._instance,
    &::Protocol::_BuffMonsterHpAdminRes_default_instance_._instance,
};
const char descriptor_table_protodef_protocol_5fgrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023protocol_grpc.proto\022\010Protocol\"\'\n\025BuffM"
    "onsterHpAdminReq\022\016\n\006add_hp\030\001 \001(\005\"9\n\025Buff"
    "MonsterHpAdminRes\022\017\n\007success\030\001 \001(\010\022\017\n\007me"
    "ssage\030\002 \001(\t2]\n\010AdminAPI\022Q\n\rBuffMonsterHp"
    "\022\037.Protocol.BuffMonsterHpAdminReq\032\037.Prot"
    "ocol.BuffMonsterHpAdminResb\006proto3"
};
static ::absl::once_flag descriptor_table_protocol_5fgrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protocol_5fgrpc_2eproto = {
    false,
    false,
    234,
    descriptor_table_protodef_protocol_5fgrpc_2eproto,
    "protocol_grpc.proto",
    &descriptor_table_protocol_5fgrpc_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_protocol_5fgrpc_2eproto::offsets,
    file_level_enum_descriptors_protocol_5fgrpc_2eproto,
    file_level_service_descriptors_protocol_5fgrpc_2eproto,
};
namespace Protocol {
// ===================================================================

class BuffMonsterHpAdminReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BuffMonsterHpAdminReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminReq, _impl_._has_bits_);
};

BuffMonsterHpAdminReq::BuffMonsterHpAdminReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuffMonsterHpAdminReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.BuffMonsterHpAdminReq)
}
BuffMonsterHpAdminReq::BuffMonsterHpAdminReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BuffMonsterHpAdminReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuffMonsterHpAdminReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE BuffMonsterHpAdminReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void BuffMonsterHpAdminReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.add_hp_ = {};
}
BuffMonsterHpAdminReq::~BuffMonsterHpAdminReq() {
  // @@protoc_insertion_point(destructor:Protocol.BuffMonsterHpAdminReq)
  SharedDtor(*this);
}
inline void BuffMonsterHpAdminReq::SharedDtor(MessageLite& self) {
  BuffMonsterHpAdminReq& this_ = static_cast<BuffMonsterHpAdminReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BuffMonsterHpAdminReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BuffMonsterHpAdminReq(arena);
}
constexpr auto BuffMonsterHpAdminReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BuffMonsterHpAdminReq),
                                            alignof(BuffMonsterHpAdminReq));
}
constexpr auto BuffMonsterHpAdminReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BuffMonsterHpAdminReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BuffMonsterHpAdminReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BuffMonsterHpAdminReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BuffMonsterHpAdminReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BuffMonsterHpAdminReq>(), &BuffMonsterHpAdminReq::ByteSizeLong,
              &BuffMonsterHpAdminReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminReq, _impl_._cached_size_),
          false,
      },
      &BuffMonsterHpAdminReq::kDescriptorMethods,
      &descriptor_table_protocol_5fgrpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BuffMonsterHpAdminReq_class_data_ =
        BuffMonsterHpAdminReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BuffMonsterHpAdminReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BuffMonsterHpAdminReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BuffMonsterHpAdminReq_class_data_.tc_table);
  return BuffMonsterHpAdminReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
BuffMonsterHpAdminReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminReq, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BuffMonsterHpAdminReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::BuffMonsterHpAdminReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 add_hp = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BuffMonsterHpAdminReq, _impl_.add_hp_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminReq, _impl_.add_hp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 add_hp = 1;
    {PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminReq, _impl_.add_hp_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void BuffMonsterHpAdminReq::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.BuffMonsterHpAdminReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.add_hp_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BuffMonsterHpAdminReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BuffMonsterHpAdminReq& this_ = static_cast<const BuffMonsterHpAdminReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BuffMonsterHpAdminReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BuffMonsterHpAdminReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.BuffMonsterHpAdminReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 add_hp = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_add_hp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_add_hp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.BuffMonsterHpAdminReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BuffMonsterHpAdminReq::ByteSizeLong(const MessageLite& base) {
  const BuffMonsterHpAdminReq& this_ = static_cast<const BuffMonsterHpAdminReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BuffMonsterHpAdminReq::ByteSizeLong() const {
  const BuffMonsterHpAdminReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.BuffMonsterHpAdminReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 add_hp = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_add_hp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_add_hp());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BuffMonsterHpAdminReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BuffMonsterHpAdminReq*>(&to_msg);
  auto& from = static_cast<const BuffMonsterHpAdminReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.BuffMonsterHpAdminReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_add_hp() != 0) {
      _this->_impl_.add_hp_ = from._impl_.add_hp_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BuffMonsterHpAdminReq::CopyFrom(const BuffMonsterHpAdminReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.BuffMonsterHpAdminReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BuffMonsterHpAdminReq::InternalSwap(BuffMonsterHpAdminReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.add_hp_, other->_impl_.add_hp_);
}

::google::protobuf::Metadata BuffMonsterHpAdminReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BuffMonsterHpAdminRes::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BuffMonsterHpAdminRes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminRes, _impl_._has_bits_);
};

BuffMonsterHpAdminRes::BuffMonsterHpAdminRes(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuffMonsterHpAdminRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.BuffMonsterHpAdminRes)
}
PROTOBUF_NDEBUG_INLINE BuffMonsterHpAdminRes::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Protocol::BuffMonsterHpAdminRes& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

BuffMonsterHpAdminRes::BuffMonsterHpAdminRes(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BuffMonsterHpAdminRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuffMonsterHpAdminRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BuffMonsterHpAdminRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:Protocol.BuffMonsterHpAdminRes)
}
PROTOBUF_NDEBUG_INLINE BuffMonsterHpAdminRes::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        message_(arena) {}

inline void BuffMonsterHpAdminRes::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
BuffMonsterHpAdminRes::~BuffMonsterHpAdminRes() {
  // @@protoc_insertion_point(destructor:Protocol.BuffMonsterHpAdminRes)
  SharedDtor(*this);
}
inline void BuffMonsterHpAdminRes::SharedDtor(MessageLite& self) {
  BuffMonsterHpAdminRes& this_ = static_cast<BuffMonsterHpAdminRes&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BuffMonsterHpAdminRes::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BuffMonsterHpAdminRes(arena);
}
constexpr auto BuffMonsterHpAdminRes::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BuffMonsterHpAdminRes),
                                            alignof(BuffMonsterHpAdminRes));
}
constexpr auto BuffMonsterHpAdminRes::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BuffMonsterHpAdminRes_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BuffMonsterHpAdminRes::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BuffMonsterHpAdminRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BuffMonsterHpAdminRes::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BuffMonsterHpAdminRes>(), &BuffMonsterHpAdminRes::ByteSizeLong,
              &BuffMonsterHpAdminRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminRes, _impl_._cached_size_),
          false,
      },
      &BuffMonsterHpAdminRes::kDescriptorMethods,
      &descriptor_table_protocol_5fgrpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BuffMonsterHpAdminRes_class_data_ =
        BuffMonsterHpAdminRes::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BuffMonsterHpAdminRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BuffMonsterHpAdminRes_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BuffMonsterHpAdminRes_class_data_.tc_table);
  return BuffMonsterHpAdminRes_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 46, 2>
BuffMonsterHpAdminRes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminRes, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BuffMonsterHpAdminRes_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::BuffMonsterHpAdminRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminRes, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BuffMonsterHpAdminRes, _impl_.success_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminRes, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminRes, _impl_.success_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(BuffMonsterHpAdminRes, _impl_.message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\7\0\0\0\0\0"
    "Protocol.BuffMonsterHpAdminRes"
    "message"
  }},
};
PROTOBUF_NOINLINE void BuffMonsterHpAdminRes::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.BuffMonsterHpAdminRes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_.success_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BuffMonsterHpAdminRes::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BuffMonsterHpAdminRes& this_ = static_cast<const BuffMonsterHpAdminRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BuffMonsterHpAdminRes::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BuffMonsterHpAdminRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.BuffMonsterHpAdminRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool success = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_success() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_success(), target);
    }
  }

  // string message = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.BuffMonsterHpAdminRes.message");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.BuffMonsterHpAdminRes)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BuffMonsterHpAdminRes::ByteSizeLong(const MessageLite& base) {
  const BuffMonsterHpAdminRes& this_ = static_cast<const BuffMonsterHpAdminRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BuffMonsterHpAdminRes::ByteSizeLong() const {
  const BuffMonsterHpAdminRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.BuffMonsterHpAdminRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string message = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // bool success = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_success() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BuffMonsterHpAdminRes::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BuffMonsterHpAdminRes*>(&to_msg);
  auto& from = static_cast<const BuffMonsterHpAdminRes&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.BuffMonsterHpAdminRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_success() != 0) {
        _this->_impl_.success_ = from._impl_.success_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BuffMonsterHpAdminRes::CopyFrom(const BuffMonsterHpAdminRes& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.BuffMonsterHpAdminRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BuffMonsterHpAdminRes::InternalSwap(BuffMonsterHpAdminRes* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata BuffMonsterHpAdminRes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protocol_5fgrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
