// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protocol_grpc.proto

#include "protocol_grpc.pb.h"
#include "protocol_grpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace Protocol {

static const char* AdminAPI_method_names[] = {
  "/Protocol.AdminAPI/BuffMonsterHp",
};

std::unique_ptr< AdminAPI::Stub> AdminAPI::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AdminAPI::Stub> stub(new AdminAPI::Stub(channel, options));
  return stub;
}

AdminAPI::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_BuffMonsterHp_(AdminAPI_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AdminAPI::Stub::BuffMonsterHp(::grpc::ClientContext* context, const ::Protocol::BuffMonsterHpAdminReq& request, ::Protocol::BuffMonsterHpAdminRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Protocol::BuffMonsterHpAdminReq, ::Protocol::BuffMonsterHpAdminRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BuffMonsterHp_, context, request, response);
}

void AdminAPI::Stub::async::BuffMonsterHp(::grpc::ClientContext* context, const ::Protocol::BuffMonsterHpAdminReq* request, ::Protocol::BuffMonsterHpAdminRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Protocol::BuffMonsterHpAdminReq, ::Protocol::BuffMonsterHpAdminRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BuffMonsterHp_, context, request, response, std::move(f));
}

void AdminAPI::Stub::async::BuffMonsterHp(::grpc::ClientContext* context, const ::Protocol::BuffMonsterHpAdminReq* request, ::Protocol::BuffMonsterHpAdminRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BuffMonsterHp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Protocol::BuffMonsterHpAdminRes>* AdminAPI::Stub::PrepareAsyncBuffMonsterHpRaw(::grpc::ClientContext* context, const ::Protocol::BuffMonsterHpAdminReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Protocol::BuffMonsterHpAdminRes, ::Protocol::BuffMonsterHpAdminReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BuffMonsterHp_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Protocol::BuffMonsterHpAdminRes>* AdminAPI::Stub::AsyncBuffMonsterHpRaw(::grpc::ClientContext* context, const ::Protocol::BuffMonsterHpAdminReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBuffMonsterHpRaw(context, request, cq);
  result->StartCall();
  return result;
}

AdminAPI::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminAPI_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminAPI::Service, ::Protocol::BuffMonsterHpAdminReq, ::Protocol::BuffMonsterHpAdminRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminAPI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Protocol::BuffMonsterHpAdminReq* req,
             ::Protocol::BuffMonsterHpAdminRes* resp) {
               return service->BuffMonsterHp(ctx, req, resp);
             }, this)));
}

AdminAPI::Service::~Service() {
}

::grpc::Status AdminAPI::Service::BuffMonsterHp(::grpc::ServerContext* context, const ::Protocol::BuffMonsterHpAdminReq* request, ::Protocol::BuffMonsterHpAdminRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Protocol
#include <grpcpp/ports_undef.inc>

